version: '3'

services:
   postgres-db:
      image: postgres:${POSTGRES_VERSION:-15-alpine}
      command: -c ssl=off
      restart: unless-stopped
      ports:
         - "16666:5432"
      environment:
         POSTGRES_DB: keycloak
         POSTGRES_USER: keycloak
         POSTGRES_PASSWORD: keycloak
      volumes:
         - postgres-data:/var/lib/postgresql/data

   kc:
      depends_on:
        - postgres-db
      image: quay.io/keycloak/keycloak:23.0.3
      restart: unless-stopped
      ports:
         - 8888:8080
      labels:
         - traefik.enable=true
         - traefik.http.routers.keycloak.rule=Host(`kcsignicat.first8.nl`)
         - traefik.http.routers.keycloak.entrypoints=websecure
         - traefik.http.routers.keycloak.tls=true
         - traefik.http.routers.keycloak.tls.certresolver=myresolver
         - traefik.docker.network=proxy
      environment:
         - KC_LOG_LEVEL=trace
         - KC_FEATURES=token-exchange,preview,declarative-user-profile
         - KC_HOSTNAME=kcsignicat.first8.nl
         - KC_DB=postgres
         - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak?ssl=allow
         - KC_DB_USERNAME=keycloak
         - KC_DB_PASSWORD=keycloak
         - KC_HOSTNAME_STRICT=false
         - KC_HTTP_ENABLED=true
         - KC_HOSTNAME_STRICT_HTTPS=false

         # Keycloak config
         - KEYCLOAK_ADMIN=admin
         - KEYCLOAK_ADMIN_PASSWORD=<password here>
         - KEYCLOAK_LOGLEVEL=${KC_LOGLEVEL:-DEBUG}
         - KC_METRICS_ENABLED=true
         - KC_HEALTH_ENABLED=true
         - KC_PROXY=edge
      volumes:
         #- ./data:/data
         #- ./importOnStartUp:/opt/keycloak/data/import
        - ./providers:/opt/keycloak/providers:ro
        - ./saml-theme:/opt/keycloak/themes/saml-theme:ro

      networks:
         - proxy
         - default
      expose:
         - 8080
      command:
         - start
         - --log-level=info,nl.first8:trace
         - --spi-theme-welcome-theme=saml-theme
   node_app:
      image: docker.first8.nl/saml-plugin-frontend:1.0-snapshot
      expose:
         - 3000
      labels:
         - traefik.enable=true
         - traefik.http.routers.keycloak.rule=Host(`kcsignicat.first8.nl`)&&(/samlconfig)
         - traefik.http.routers.keycloak.entrypoints=websecure
         - traefik.http.routers.keycloak.tls=true
         - traefik.http.routers.keycloak.tls.certresolver=myresolver
         - traefik.docker.network=proxy

      depends_on:
         - kc

volumes:
   postgres-data:

networks:
   proxy:
      name: proxy
      external: true
